# Generated by Django 4.2 on 2023-04-06 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_studentgroup_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='name',
            new_name='full_name',
        ),
        migrations.AddField(
            model_name='student',
            name='username',
            field=models.CharField(default='test', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
