# Generated by Django 4.1.2 on 2023-04-19 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_student_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='time',
            field=models.DateField(default='2023-04-19'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lecture',
            name='venue',
            field=models.CharField(default='2023-04-19', max_length=255),
            preserve_default=False,
        ),
    ]
