# Generated by Django 4.1.2 on 2023-04-19 18:55

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_lecture_time_lecture_venue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='time',
            field=models.CharField(max_length=5, validators=[core.models.validate_time_format]),
        ),
    ]
