# Generated by Django 4.1.2 on 2023-04-20 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_lecture_student_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='lecturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='assignments', to='core.lecturer', blank=False),
            preserve_default=False,
        ),
    ]
