# Generated by Django 4.1.2 on 2023-04-28 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_assignment_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturer',
            name='password',
            field=models.CharField(default='123', max_length=255),
            preserve_default=False,
        ),
    ]
