# Generated by Django 4.1.2 on 2023-04-28 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_lecturer_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='lecturer',
            new_name='created_by_lecturer',
        ),
        migrations.RenameField(
            model_name='assignment',
            old_name='student',
            new_name='created_by_student',
        ),
    ]
