# Generated by Django 4.1.2 on 2023-04-28 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_venue'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='venue',
            field=models.ForeignKey(
                default=2, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='core.venue'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lecture',
            name='venue',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name='lectures', to='core.venue'),
        ),
    ]
