# Generated by Django 4.1.2 on 2023-04-28 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_assignment_venue_alter_lecture_venue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='venue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='core.venue'),
        ),
    ]
