# Generated by Django 4.1.2 on 2023-04-30 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_rename_created_by_lecturer_assignment_lecturer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='student_groups',
            field=models.ManyToManyField(to='core.studentgroup'),
        ),
    ]
